### ISSUE TITLE
Create an 'About' Page with Dynamic Content

### ISSUE THREAD

**Issue by ghost** [aish12/parksrus#10]
The Phase 1 of this milestone requires an 'About' page which details the project's collaborators and integrates with the Github API to provide information related to tracking of our commit history, unit tests, and issues.

The 'About' Page must have:

- [x] description of the site, its purpose, its intended users
- [ ] explanation of the interesting result of integrating disparate data
- [x] the group name
- [x] the group members

For Each Member:
- [x] name
- [x] photo
- [x] bio
- [x] major responsibilities
- [x] no. of commits
- [x] no. of issues
- [ ] no. of unit tests

Statistics:
- [x] total no. of commits
- [x] total no. of issues
- [ ] total no. of unit tests

Data:
- [x] links to the data sources
- [ ] description of how each was scraped

Tools:
- [x] tools used
- [x] describe their use
- [ ] special focus on optional tools that were not required
- [x] a link to the GitBook report
- [x] a link to the GitHub repo

This should take 2 hours.

**Comment by aish12** [comment]
What may be some good ideas to integrate information about the nonrequired tools we used without making the website look gacky?

**Comment by ChimdinduDenalexOrakwue** [comment]
@aish12 We can just include them along with the other tools. @trentonbeckendorff @danielczheng @b-chen thoughts?

**Comment by ghost** [comment]
@ChimdinduDenalexOrakwue I believe that is an appropriate solution stylistically. **To the end users of our website, the distinction between required and optional tools is essentially a moot point.** I believe in terms of preserving the page's current design we would be best served by following the proposal you suggested.

@aish12 How can we integrate the "with special attention to" aspect while not overloading the design? Perhaps a tooltip upon hovering over each tool's card? **As a rough estimate, I believe this would take 1 - 2 hours to implement**.

**Comment by danielczheng** [comment]
@trentonbeckendorff @aish12 I don't think we should give special attention to any of the tools. I agree in that we should just have them under "Our Tools", as there really isn't a reason to hold one tool over the other in the eyes of the user (unless we're **really thankful**).

**Comment by aish12** [comment]
This item took 6 hours to complete.
