### ISSUE TITLE
Create Five User Stories (Storyboarding)

### ISSUE THREAD

**Issue by ghost** [aish12/parksrus#11]
As an integration of the course's Extreme Programming concepts, we are required to create and document 5 User Stories via Github's Project Board feature.

- [ ] user stories must be described in three sentences or less
- [ ] estimate them, include assumptions
- [ ] discuss them
- [ ] refine the estimates
- [ ] implement them
- [ ] track how long each took

**Comment by danielczheng** [comment]
Completed. See 'Storyboard' under Projects tab.

**Comment by danielczheng** [comment]
Completed. See 'Storyboard' under Projects tab.
