### ISSUE TITLE
Create a Navigation Bar

### ISSUE THREAD

**Issue by ghost** [aish12/parksrus#13]
The project's requirements specify that each page must have a Navigation Bar available for users to transition between our site's pages.

The Navigation Bar must link to the following:
- [x] Splash
- [x] Images
- [x] Cities
- [x] Amusement Parks

This should take 1 hour.

**Comment by aish12** [comment]
Will it be simple to add more tabs to the Nav bar if we choose?

**Comment by ChimdinduDenalexOrakwue** [comment]
Yeah it should be pretty easy, @trentonbeckendorff how long do you think it might take?

**Comment by ghost** [comment]
The [NavigationBar](https://github.com/aish12/parksrus/blob/master/app/parksrus-frontend/src/components/NavigationBar/NavigationBar.js) is primarily a wrapper component for React-Bootstrap's NavBar element with specific routes defined for each of our GridPages (Snapshots, Parks, Cities) and the About page. It can easily be extended to include additional links, which would require an additional insertion of the route in the [Main.js](https://github.com/aish12/parksrus/blob/master/app/parksrus-frontend/src/components/Main/Main.js) component. **This could be completed in a matter of minutes.**

If we decide to add a significant number of links, we could always transition to including a dropdown in the NavBar, such as in this [example in React-Bootstrap's guide](https://react-bootstrap.github.io/components/navbar/#navbars-basic). **I estimate this change (excluding time to create the pages linked to) would take at most 1-2 hours.**

**Comment by aish12** [comment]
This item took 1 hour to complete.
