### ISSUE TITLE
Create Grid Pages for Park, City, and Image Models

### ISSUE THREAD

**Issue by ghost** [aish12/parksrus#16]
Each database model (Amusement Parks, Cities, and Images) should have a corresponding page with a grid layout that reveals all stored instances of the model. 

Each model's page should have:

- [ ] Grid of All Model Instances
- [ ] Three Attributes Per Model
- [ ] Links to Other Model Instances

This should take 3 hours.

**Comment by ghost** [comment]
We need to re-open this issue as it is not yet complete.

**Comment by aish12** [comment]
Will all of these models have the same image or will we have a variety of images for each of the models? Will we be able to link those images to each other?

**Comment by ChimdinduDenalexOrakwue** [comment]
@aish12 each model will have its own image, and the snapshot model is an image in itself. So each city will link to the parks in the city and photos taken in the city. Each park will link to the city it is in and the photos taken in the park. Each snapshot will link to it's associated park and city.

**Comment by ghost** [comment]
@ChimdinduDenalexOrakwue as a minor clarification, we currently only have database instances with a single link to other models. I.e. NY City only has a reference to a single theme park out of the 18. Once we implement scraping, we can expect these grids to be much more robust in terms of content. **How much time are you estimating to implement a web scraper for each of the REST APIs?**

**Comment by danielczheng** [comment]
@ChimdinduDenalexOrakwue @trentonbeckendorff @aish12 Also need clarification on 'Snapshots' model. Will the snapshots include pictures taken of the 'City' but not necessarily in a 'Park'? Or will all 'Snapshots' in the 'City' page be 'Park'-related?

**Comment by ChimdinduDenalexOrakwue** [comment]
@danielczheng all snapshots in the city page will be park related

**Comment by aish12** [comment]
This item took 3 hours to complete.
