### ISSUE TITLE
Create Example Description Pages for Park, City, and Image Models

### ISSUE THREAD

**Issue by danielczheng** [aish12/parksrus#22]
When you click on a model item (Amusement Parks, Cities, or Images), you should be led to a description page about it. We should have at least 3 examples of each model.

Each description page should have:

- [ ] Related Media (Image, Video, etc.)
- [ ] Relevant Data About the Item
- [ ] Links to Other Model Instances

This should take 3 hours.

**Comment by ghost** [comment]
We need to re-open this issue as it is not yet complete.

**Comment by danielczheng** [comment]
Which examples should we be using for now? And anyone have ideas on how the pages should look without being too cluttery? We essentially need to design for three different types of pages, three examples each, so this might take awhile. **Estimate about 4-8 hours. Thoughts?**

**Comment by aish12** [comment]
This story took 3 hours to complete.
