### ISSUE TITLE
Implement Google Places Scraping

### ISSUE THREAD

**Issue by ChimdinduDenalexOrakwue** [aish12/parksrus#25]
Expected to take 1 hour
Actually took 1 hour

**Comment by aish12** [comment]
Are the reviews from the google places scraping useful? Do they compare to help well?

**Comment by ChimdinduDenalexOrakwue** [comment]
The Google Places reviews are on a scale from 0.0 to 5.0, which will be good for sorting or ranking later on. This should take a day or so of work to do
