### ISSUE TITLE
Implement Pagination

### ISSUE THREAD

**Issue by aish12** [aish12/parksrus#38]
Expected to take 4 hours
Actually took 3 hours

**Comment by ChimdinduDenalexOrakwue** [comment]
Already implemented (app/app.py line #20). Closing for now

**Comment by aish12** [comment]
How will we determine how many items should be on each page?

**Comment by ChimdinduDenalexOrakwue** [comment]
We can decide based on how the # of items looks on each page.

**Comment by ChimdinduDenalexOrakwue** [comment]
Since this feature already comes with Flask-Restless, implementing it on the backend should only take 30min to an hour

**Comment by ChimdinduDenalexOrakwue** [comment]
@trentonbeckendorff How long do you think it will take to implement on the front-end?

**Comment by danielczheng** [comment]
As suggestion, we can also let the customer decide how many items appear per page, i.e. 10, 25, 50, 100 per page
Also, somewhat related, we could look into infinity scroll as an alternative

**Comment by ChimdinduDenalexOrakwue** [comment]
Yeah those are pretty good ideas, we can stick to normal pagination now and then experiment later if we choose to.

**Comment by danielczheng** [comment]
Would still like thoughts @trentonbeckendorff, but I think it might take a few hours, since this is a feature for the grid pages.
