### ISSUE TITLE
Refine data on many instances of each model

### ISSUE THREAD

**Issue by aish12** [aish12/parksrus#52]
We expected this to take 3-4 hours and it took 2.

**Comment by aish12** [comment]
This seems like a good idea. Should we start with the instances on the first few pages of each model? If there's missing information should we exclude the instance or fill in info from other sources?

**Comment by ChimdinduDenalexOrakwue** [comment]
I think given the magnitude of the data we have already, dropping instances with unfilled fields shouldn't be a problem. This should take long to do (maybe a day tops) with a few SQL queries.
