### ISSUE TITLE
Add filtering

### ISSUE THREAD

**Issue by aish12** [aish12/parksrus#54]
We expected this to take 5 hours, and it took 8 hours.

**Comment by aish12** [comment]
For filtering, one of the things we discussed was filtering by state. 50 options for filtering may seem like a lot. Thoughts?

**Comment by ChimdinduDenalexOrakwue** [comment]
I think its alright as long as the way we display it isn't cumbersome. Flask Restless already has filtering, so implementing it on the frontend should only take a day or two.

**Comment by danielczheng** [comment]
Cities and Parks can be filtered by state. Can snapshots also be filtered by location/state? And what other parameters can we filter by?

**Comment by ChimdinduDenalexOrakwue** [comment]
Snapshots can be filtered by city and state too
