### ISSUE TITLE
Add Searching

### ISSUE THREAD

**Issue by aish12** [aish12/parksrus#56]
We expected this to take about 10 hours, and it took 7.

**Comment by aish12** [comment]
When we search, should we try to look for hits for a few attributes or should we search through all?

**Comment by ChimdinduDenalexOrakwue** [comment]
We should look through all attributes that make sense to search on. On the backend i'll add new endpoints for whoosh search. On the frontend we can just call the API with query values. This shouldn't take more than a day.

**Comment by danielczheng** [comment]
So are we doing a general search and specific searches for all three models?

**Comment by ChimdinduDenalexOrakwue** [comment]
We are doing a general search that searches everything
