### ISSUE TITLE
Add Sorting

### ISSUE THREAD

**Issue by aish12** [aish12/parksrus#57]
We expect this to take around 10 hours, it took 7.

**Comment by aish12** [comment]
What sort of things should we sort on for each model?

**Comment by ChimdinduDenalexOrakwue** [comment]
We could sort on fields that have numerical values and things like the name we can sort in alphabetical order

**Comment by ChimdinduDenalexOrakwue** [comment]
Flask Restless already let's us sort via the API, so we just need to implement it on the front end. It'll probably take a day or so

**Comment by danielczheng** [comment]
Cities can be sorted by city, state, num_parks; Parks can be sorted by name, city, state, rating; Snapshots can be sorted by views. Any of these can be sorted in alphanum order ASC/DESC. Is there anything else I missed?

**Comment by ChimdinduDenalexOrakwue** [comment]
This ended up taking a day
