### ISSUE TITLE
Refine Unit Tests

### ISSUE THREAD

**Issue by aish12** [aish12/parksrus#58]
We expected this to take 6 hours, and it took 4 hours.

**Comment by aish12** [comment]
What sorts of things should we add unit tests for?

**Comment by ChimdinduDenalexOrakwue** [comment]
We should add more tests for the new search endpoints we made and any new helper functions we make. This should take a day.

**Comment by danielczheng** [comment]
Working on Mocha. @trentonbeckendorff Need to know the new components to test on, as well as which attributes/props to be aware of.

**Comment by b-chen** [comment]
Tests for filtering and sorting are done. Need to work on searching tests
