### ISSUE TITLE
More information on cards

### ISSUE THREAD

**Issue by JeffJiang42** [aish12/parksrus#62]
As users, we would like to see more information displayed on the cards to give more information at a glance. In addition, we would like to be able to filter by the information displayed on the cards. For example, one of the options for filtering is by city, but this information is not displayed on the cards.

**Comment by ghost** [comment]
I've exposed additional attributes for our models on their respective cards for the parks and cities models. Cities now display an abbreviated description of approximately 100 words,  and parks now display the city that they are located closest to. I estimated that this change would require 2 hours of time, but it only required 1 hour to complete.
