### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by JeffJiang42** [aish12/parksrus#64]
The pagination component behaves quite strangely. At the moment, the default page for grids is 2, and clicking on buttons on the pagination component results in inconsistent behavior. For example, some page buttons do not respond, and the next page button works sporadically. In addition, after filtering and sorting, sometimes the pagination component disappears.

**Comment by aish12** [comment]
Expected time to complete is 4 hours.

**Comment by danielczheng** [comment]
This took about 3 hours.
