### ISSUE TITLE
Search result clarification 

### ISSUE THREAD

**Issue by JeffJiang42** [aish12/parksrus#66]
For search results, we would like to see more information on the results cards, like the number of parks, the number of nearby attractions, or for snapshots, the location or park. Currently, the searches only seem to match tags, but a user would expect a search for San Francisco to find snapshots taken in San Francisco. If this is already the case, some clarification on the snapshot cards (e.g. displaying location/park) would help a user in understanding and processing search results.

**Comment by aish12** [comment]
Expected time to complete is 2 hours.

**Comment by ghost** [comment]
Hello,

I've updated the search results to include additional information on the search cards to enable users to identify information related to the number of nearby attractions, and the park and city associated with the given snapshot! I estimated this would take an hour, in actuality it took closer to 3 hours.
