### ISSUE TITLE
Filter interaction

### ISSUE THREAD

**Issue by JeffJiang42** [aish12/parksrus#67]
As users, we expect that multiple different filters should interact in an intuitive manner. Currently, the multi-value filters work as expected by filtering as an OR, but trying to filter by both city and state does not seem to perform an AND operation as one might expect. For example, filtering by state for Texas and then filtering the city by San Antonio should display parks found only in San Antonio. While this example might not be too meaningful if more filters are added a user might expect this kind of interaction.

**Comment by aish12** [comment]
Expected time to complete is 2 hours.

**Comment by danielczheng** [comment]
This took about 10 mins. We have taken out the "Filter by city" in the Parks Page due to its complicated nested structure.
