### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by JeffJiang42** [aish12/parksrus#70]
Some of the documentation is a bit unclear, which would hinder the ability for an API consumer to process the data. For example, in the Parks documentation, one of the attributes for a park is named “photos”, but when querying the API returns JSON objects with an attribute name “snapshots.” Updating and clarifying the documentation would be extremely beneficial to an API consumer.

**Comment by ChimdinduDenalexOrakwue** [comment]
Seems like we need to update the documentation to match our current API. Est time to complete this user story is 1 day

**Comment by ChimdinduDenalexOrakwue** [comment]
Actual time to complete this story was 1 day
