### ISSUE TITLE
API filtering

### ISSUE THREAD

**Issue by JeffJiang42** [aish12/parksrus#71]
As API consumers, we would like API calls that allow us to filter results. This would help us find specific data rather than have us parse all the data ourselves.

**Comment by ChimdinduDenalexOrakwue** [comment]
There are already filtering parameters in our API since we used Flask Restless, I think we just need to update the documentation to match which. Est time to complete this user story is 1 day

**Comment by ChimdinduDenalexOrakwue** [comment]
Closing. Actual time was 1hr
